# Dependency Review Configuration
# This configuration addresses the common license and scorecard issues in JS/TS projects

# OpenSSF Scorecard configuration
scorecard:
  # Lower threshold to accommodate npm ecosystem realities
  # Many essential packages have scores below 3.0 due to GitHub metadata requirements
  threshold: 2.0

# License allowlist includes common permissive licenses used in JS/TS ecosystem
licenses:
  # Core permissive licenses
  allow:
    - MIT
    - Apache-2.0
    - BSD-2-Clause
    - BSD-3-Clause
    - ISC
    # Additional permissive licenses commonly found in build tools
    - 0BSD
    - CC0-1.0
    - CC-BY-4.0
    # Unicode-related licenses for internationalization libraries
    - LicenseRef-scancode-unicode
  
  # Only block clearly restrictive licenses
  deny:
    - GPL-2.0
    - GPL-3.0
    - AGPL-3.0
    - LGPL-2.1
    - LGPL-3.0

# Exclude known false positives and temporary files
excludes:
  # Backup directories created by deduplication scripts
  - ".deduplication-backups/**/*"
  # Node modules (handled by package-lock.json analysis)
  - "node_modules/**/*"
  # Build artifacts
  - "dist/**/*"
  - "build/**/*"
  # Temporary files
  - "*.tmp"
  - "temp/**/*"

# Vulnerability settings
vulnerabilities:
  # Focus on actionable moderate+ vulnerabilities
  fail-on-severity: moderate
  # Allow advisories that are commonly false positives for frontend projects
  allow-ghsas:
    - GHSA-67hx-6x53-jw92  # ReDoS in semver (build-time only)
    - GHSA-qwcr-r2fm-qrc7  # Path traversal in resolve-path (dev dependency)

# Supply chain settings
supply-chain:
  # Allow common package patterns that may have lower scores
  allow-dependencies-with-scorecard-below-threshold:
    # Essential build tools that may have lower scores
    - "rollup"
    - "vite"
    - "esbuild"
    # Babel ecosystem (maintained by core team but lower GitHub scores)
    - "@babel/*"
    # PostCSS ecosystem
    - "postcss*"
    - "@csstools/*"
    # Common utilities with established track records
    - "lodash"
    - "cross-spawn"
    - "cac"
    - "blake3-wasm"
    - "deepmerge"
    - "common-tags"
    - "@jridgewell/*"
    - "@ampproject/remapping"
    - "@apideck/better-ajv-errors"

# Comment patterns for complex licenses
comments:
  license-patterns:
    # Multi-license packages where any of the licenses is acceptable
    - pattern: "Apache-2.0 AND BSD-2-Clause AND CC0-1.0 AND ISC AND MIT"
      reason: "Vite and Rollup use multiple permissive licenses - all are acceptable"
    - pattern: "0BSD AND ISC AND MIT"
      reason: "Rollup uses multiple permissive licenses - all are acceptable"  
    - pattern: "CC0-1.0 AND MIT"
      reason: "Lodash dual-licensed under permissive licenses"
    - pattern: "LicenseRef-scancode-unicode AND MIT"
      reason: "Unicode libraries with standard Unicode consortium license + MIT"
