# Codecov Configuration
# Documentation: https://docs.codecov.com/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 75%          # Decreased from 90% to more reasonable level
        threshold: 5%        # Increased from 1% (more lenient)
        base: auto
    patch:
      default:
        target: 70%          # Decreased from 85% to more achievable level
        threshold: 10%       # Increased from 3% (much more lenient)

  ignore:
    - "test/**/*"
    - "e2e/**/*"
    - "src/dev/**/*"
    - "**/*.test.ts"
    - "**/*.spec.ts"
    - "**/*.d.ts"
    - "**/*.config.ts"
    - "dist/**/*"
    - "node_modules/**/*"
    - "scripts/**/*"
    - "docs/**/*"
    - "coverage/**/*"

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

flags:
  unittests:
    paths:
      - src/
    carryforward: true
  integration:
    paths:
      - src/
    carryforward: true
