# Cloudflare Workers Configuration
name = "simulation-worker"
account_id = "362c458c58efc6b65b7005148383403d"
workers_dev = true

# Add main entry point for Workers
main = "workers/index.js"

compatibility_date = "2025-07-15"
