# Cloudflare Pages Configuration
name = "organism-simulation"
compatibility_date = "2024-01-01"

[env.production]
vars = { NODE_ENV = "production" }

[env.preview] 
vars = { NODE_ENV = "staging" }

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Environment variables
[vars]
VITE_APP_NAME = "Organism Simulation"
VITE_APP_VERSION = "1.0.0"
VITE_ENABLE_DEBUG = "false"
VITE_ENABLE_ANALYTICS = "true"

# Pages configuration
pages_build_output_dir = "dist"

# Redirects and headers
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
