# Cloudflare Pages Configuration
name = "organism-simulation"
compatibility_date = "2024-01-01"

# Pages build configuration
pages_build_output_dir = "dist"

[build]
command = "npm run build"
cwd = "."

# Environment variables for production
[env.production.vars]
NODE_ENV = "production"
VITE_APP_URL = "https://organisms.andernet.dev"
VITE_APP_NAME = "Organism Simulation"
VITE_APP_VERSION = "1.0.0"
VITE_ENABLE_DEBUG = "false"
VITE_ENABLE_ANALYTICS = "true"

# Environment variables for preview/staging
[env.preview.vars]
NODE_ENV = "staging"
VITE_APP_URL = "https://organisms-staging.andernet.dev"
VITE_APP_NAME = "Organism Simulation (Staging)"
VITE_APP_VERSION = "1.0.0"
VITE_ENABLE_DEBUG = "true"
VITE_ENABLE_ANALYTICS = "false"
