name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "Feature: [Brief Description]"
labels: ["enhancement", "feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand what you'd like to see added to the simulation.
  
  - type: dropdown
    id: type
    attributes:
      label: Feature Type
      description: What kind of feature is this?
      options:
        - New organism behavior
        - Educational content
        - UI/UX improvement
        - Performance enhancement
        - Developer tool
        - Integration
        - Other
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - High (would significantly improve my use case)
        - Medium (would be helpful)
        - Low (nice to have)
    validations:
      required: true
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "Currently, users cannot... which makes it difficult to..."
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: "I would like to be able to..."
    validations:
      required: true
  
  - type: textarea
    id: user-stories
    attributes:
      label: User Stories
      description: Who would benefit and how?
      placeholder: |
        - As a teacher, I want to...
        - As a student, I want to...
        - As a researcher, I want to...
    validations:
      required: false
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered other approaches?
      placeholder: "Alternative approaches might be..."
    validations:
      required: false
  
  - type: textarea
    id: examples
    attributes:
      label: Examples
      description: Any examples from other tools or implementations?
      placeholder: "Similar features exist in..."
    validations:
      required: false
  
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Mockups, diagrams, or other relevant information
      placeholder: "Any other context, screenshots, or examples..."
    validations:
      required: false
  
  - type: checkboxes
    id: roadmap
    attributes:
      label: Roadmap Alignment
      description: Is this feature already in our roadmap?
      options:
        - label: I checked the [Product Roadmap](../docs/development/PRODUCT_ROADMAP.md) and this feature is not listed
          required: false
        - label: This feature aligns with the project's educational mission
          required: false
